export class Vitals{
    patiId: string='';
    visitId: string='';
    doctId: string='';
    edocId: string='';
    empId: string='';
    // height1?: number;
    height1?: number | null = null;
    weight1?: number | null = null;
    temp1?: number | null = null;
    pulse1?: number | null = null;
    maxBp?: number | null = null;
    minBp?: number | null = null;
    rr1?: number | null = null;
    unit1?: string;
    hCircum?: number | null = null;
    wCircum?: number | null = null;
    bWeight?: number | null = null;
    pGrbs?: string;
    maxBpLeft?: number | null = null;
    minBpLeft?: number | null = null;
    pTempUnit?: string="C";
    pSpo2?: number | null = null;
    pNurseNote?: string;
    
    pNurseRemarks?: string;
    pPainAssessment?: string='0';
    pLocation?: string;
    pRemarks?: string;
    pAssessmentDistrus?: string;
    pBg?: string;
    pFsh?: string;
    pSupplemental?: string;
    pLevelOfConsciousness?: string;
    pDuration?: string;
    pPainRadiating?: string;
    pOnsetPain?: string;
    pClinicTriage?: string;
    pPriority?: string;
    pBpDown?: string;
    pBpUp?: string;
    pHealthEducation?: string;
    pUrineAcr?: string;
    pHba1c?: string;
    pVitaminD?: string;
    pNotes?: string;
    pBldGrpId?: string;
    BLD_GRP_ID?:string;
    P_BG?:string;
    BLD_GRP_NAME?:string;
}