export interface PatientBookingDto{
  patI_ID?: string;
  patI_OPNO?: string;
  patI_FIRST_NAME?: string;
  patI_GENDER?: string;
  patI_MOBILE?: string;
  bK_MESSAGES?: string;
  bK_REMARKS?: string;
  realL_STATUS?: string;
  bK_CANCEL_DATE?: string;
  apP_CONFIRM?: string;
  nurses?: string;
  prC_NAME?: string;
  prC_BK_MACHINE_NAME?: string;
  creatE_USER?: string;
  creatE_DATE?: string;
  prC_BK_ID?: string;
  prC_BK_ROOM_ID?: string;
  machinE_ID?: string;
  apP_CONFIRM_REMARK?: string;
  apP_CONFIRMED_ON?: string;
  apP_CONFIRMED_BY?: string;
  bK_CANCEL_REASON?: string;
  CANCEL_USER?: string;
  prC_BK_CANCEL?: string;
  statuS_REALL?: string;
  statuS_CANCEL?: string;
  statuS_APP_CONFIRM?: string;
  prC_BK_DATE?: string;
  prC_BK_TOKEN_NO?: string;
  status?: string;
  remarks?: string;
  createD_USER?: string;
  visiT_DATE?: string;
  visiT_TIME?: string;
  cprno?: string;
  prC_BK_ROOM_NAME?: string;

}